name: moses
channels:
  - pytorch
  - rdkit
  - defaults
dependencies:
  - _pytorch_select=0.1
  - absl-py=0.11.0
  - aiohttp=3.7.2
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - boost=1.59.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cachetools=4.1.1
  - certifi=2020.11.8
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - colorama=0.4.4
  - cryptography=3.2.1
  - cudatoolkit=11.0.221
  - cycler=0.10.0
  - dataclasses=0.7
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.4
  - google-auth=1.23.0
  - google-auth-oauthlib=0.4.2
  - grpcio=1.31.0
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - idna_ssl=1.1.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - kiwisolver=1.3.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libuv=1.40.0
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.3
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - multidict=4.7.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.3
  - networkx=2.5
  - ninja=1.10.2
  - nodejs=10.13.0
  - notebook=6.1.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1h
  - packaging=20.7
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - protobuf=3.13.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.7.2
  - pyjwt=1.7.1
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.12
  - python-dateutil=2.8.1
  - pytorch=1.7.0
  - pytz=2020.4
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - qt=5.9.7
  - rdkit=2017.09.1
  - requests=2.25.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scipy=1.5.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=50.3.2
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=4.3.3
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.0
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - yarl=1.5.1
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - ax-platform==0.1.9
    - botorch==0.2.1
    - fcd-torch==1.0.7
    - future==0.18.2
    - gpytorch==1.3.0
    - joblib==0.17.0
    - plotly==4.13.0
    - pomegranate==0.12.0
    - pyyaml==5.3.1
    - retrying==1.3.3
    - scikit-learn==0.23.2
    - threadpoolctl==2.1.0
    - tqdm==4.54.0
